#!/usr/bin/env python

from __future__ import print_function

import yaml
import os
import sys

configs=["default.conf.yaml"]

for i in sys.argv[1:]:
    configs.append("{0}.conf.yaml".format(i))

# TODO: This does not cover globbing links
print(configs)
for config in configs:
    stream = open(config, "r")
    conf = yaml.load(stream)

    for section in conf:
         if 'link' in section:
             for target in section['link']:
                 realpath = os.path.expanduser(target)
                 if os.path.islink(realpath):
                     print("Removing ", realpath)
                     os.unlink(realpath)

